PEAP 14
PGS-dev/event-pwa pull request #3
Opened 2017-05-23 13:17 UTC by mkrds

Basic unit tests of AdminPage, EventsList and EventDetails components done - will have to be rewritten anyway since we're switching state management to Vuex.

2017-05-24 09:26 UTC, Qwal requested changes

2017-05-24 09:26 UTC, Qwal commented on test/unit/specs/App.spec.js
> +/*
usuń ten plik

2017-05-24 09:26 UTC, Qwal commented on src/App.vue
> +
tu miały wskoczyć style do offline message?

2017-05-24 11:23 UTC, mkrds commented on src/App.vue
> +
tak ale ostatecznie zostaly w styles.scss bo jednak offline message musi byc dostepne globalnie

2017-05-25 14:27 UTC, Qwal approved these changes

2017-05-25 14:27 UTC, merged